2024FALL-SWPP/team-project-for-2024-fall-swpp-team-05

RunInBoots/Assets/Resources/LevelObject/HatObject.prefab
RunInBoots/Assets/Resources/LevelObject/HatObject.prefab.meta
RunInBoots/Assets/Scripts/Enums/HatEnums.cs
RunInBoots/Assets/Scripts/Enums/HatEnums.cs.meta
RunInBoots/Assets/Scripts/LevelDesignTool/Hat.cs
RunInBoots/Assets/Scripts/LevelDesignTool/Hat.cs.meta
RunInBoots/Assets/Scripts/LevelDesignTool/HatObject.cs
RunInBoots/Assets/Scripts/LevelDesignTool/HatObject.cs.meta
RunInBoots/Assets/Scripts/LevelDesignTool/NormalHat.cs
RunInBoots/Assets/Scripts/LevelDesignTool/NormalHat.cs.meta
RunInBoots/Assets/Scripts/LevelDesignTool/TigerHat.cs
RunInBoots/Assets/Scripts/LevelDesignTool/TigerHat.cs.meta
RunInBoots/Assets/Scripts/UnitModules/BattleModule.cs
RunInBoots/Assets/Scripts/UnitModules/CamouflageModule.cs
RunInBoots/Assets/Scripts/UnitModules/CamouflageModule.cs.meta

-
- Implement CamouflageModule
- Add public var preAttacked to register Unequip function
- Add HatObject Prefab for testing
---

[TASK-P42] Implement CamouflageModule

---

RunInBoots/Assets/Scripts/LevelDesignTool/GridManager.cs

[S3-B5] Fix #33/issue

---

RunInBoots/Assets/Scripts/LevelDesignTool/LevelLoader.cs

모든 콜라이더의 x축 크기를 미세하게 줄이고, 그렇게 생긴 빈 영역에 외곽 세로 선 당 하나만 발생하는 edge collider 생성
---
---
linter.yml:
---
name: Lint
push: null
jobs:
build:
name: Lint
permissions:
contents: read
packages: read
steps:
with:
fetch-depth: 0 …

예외 케이스에 대한 work around로 edge collider 적용

---

RunInBoots/Assets/Scripts/UnitModules/ActionSystem.cs
RunInBoots/Assets/Scripts/UnitModules/TransformModule.cs

---
---
linter.yml:
---
name: Lint
push: null
jobs:
build:
name: Lint
permissions:
contents: read
packages: read
steps:
with:
fetch-depth: 0
env:

[ISSUE-B9] 점프 높이 오류 수정

---

RunInBoots/Assets/Scripts/UnitModules/ActionSystem.cs

---
---
linter.yml:
---
name: Lint
push: null
jobs:
build:
name: Lint
permissions:
contents: read
packages: read
steps:
with:
fetch-depth: 0
env:

[ISSUE-B7] Fix Risable Condition Checking

---

RunInBoots/Assets/Scripts/States/StageState.cs

---
---
+) 전투 모듈 사망 이벤트에 LifeOver 처리 추가
linter.yml:
---
name: Lint
push: null
jobs:
build:
name: Lint
permissions:
contents: read
packages: read
steps:
with:
fetch-depth: 0
env:
GITHUB_TOKEN: ${{ …

[TASK-P68] 모듈 통합 완료 - 목숨 값 변동 시 저장 및 스테이지 클리어 정보 저장

---

RunInBoots/Assets/Scripts/States/StageState.cs

타이틀 씬 테스트 중 추가 이슈 발견, 새 StageState Constructor => 기존 StageState Exit 순으로 불리며 최근 스테이지가 덮어 써짐. 우선 실행 순서 변경으로 대처.
---
---

[TASK-P68] 최근 스테이지 저장 시점 버그 수정, Constructor -> Start로 이동

---

RunInBoots/Assets/Scripts/Events.meta
RunInBoots/Assets/Scripts/Events/AnimatorEvent.cs
RunInBoots/Assets/Scripts/Events/AnimatorEvent.cs.meta
RunInBoots/Assets/Scripts/Events/DelayEvent.cs
RunInBoots/Assets/Scripts/Events/DelayEvent.cs.meta
RunInBoots/Assets/Scripts/Events/ProducingEvent.cs
RunInBoots/Assets/Scripts/Events/ProducingEvent.cs.meta
RunInBoots/Assets/Scripts/Managers/GameManager.cs
RunInBoots/Assets/Scripts/Objects/Catnip.cs
RunInBoots/Assets/Scripts/Objects/GoalPoint.cs
RunInBoots/Assets/Scripts/Objects/Pipe.cs
RunInBoots/Assets/Scripts/Objects/StartPoint.cs
RunInBoots/Assets/Scripts/States/StageState.cs
RunInBoots/Assets/Scripts/UnitModules/BattleModule.cs

---
---
linter.yml:
---
name: Lint
push: null
jobs:
build:
name: Lint
permissions:
contents: read
packages: read
steps:
with:
fetch-depth: 0
env:

S3 p44, p45 연출 컨텐츠 구현

---

RunInBoots/Assets/Scripts/Managers/GameManager.cs
RunInBoots/Assets/Scripts/UnitModules/CamouflageModule.cs
RunInBoots/Assets/Scripts/UnitModules/TestCamouflageModule.cs

close #52 
- CamouflageModule의 기능이 정상적으로 작동하는지 테스트합니다.
- GameManager.Awake()가 호출될 때 테스트를 수행합니다.

S3_p60-3 test camouflage module

---

RunInBoots/Assets/Scripts/States/StageState.cs

기존 : StageState에 의한 PlayerKill이 GameOver 여부 관리
수정 후 : LifeOver에서 목숨 변동 시 GameOver 판정
---
---

[TASK-P68] GameOver 처리 추가 이슈 수정 - 모든 GameOver로직이 LifeOver를 타도록 변경

---

RunInBoots/Assets/Prefabs/CameraObject.prefab
RunInBoots/Assets/Scripts/States/StageState.cs

perspective camera 적용, 화각 30에 distance 60
---
---
linter.yml:
---
name: Lint
push: null
jobs:
build:
name: Lint
permissions:
contents: read
packages: read
steps:
with:
fetch-depth: 0
env:

S4 p90 camera improve

---

RunInBoots/Assets/Scripts/Managers/OutGameManager.cs
RunInBoots/Assets/Scripts/Utility/UserData.cs

[S4-B19] fix #65

---

RunInBoots/Assets/Resources/PlayerController.prefab
RunInBoots/Assets/Scripts/Managers/GameManager.cs
RunInBoots/Assets/Scripts/States/StageState.cs
RunInBoots/Assets/Scripts/UnitModules/CamouflageModule.cs

[S4-TASK17] fix #61

---

RunInBoots/Assets/Scripts/UnitModules/ActionSystem.cs

인풋 지연 해결 및 OnLand 조건 체크 보강
B25
Input.GetAxis -> Input.GetAxisRaw
OnLand BoxCast를 원점서 처리
---
---

[Issue-B25] 인풋 지연 해결 및 OnLand 조건 체크 보강

---

RunInBoots/Assets/Art/Animation/UI/spawn_ui.anim
RunInBoots/Assets/Resources/SpawnUI.prefab
RunInBoots/Assets/Resources/StageUIObject/SpawnHeartIcon.prefab
RunInBoots/Assets/Resources/StageUIObject/SpawnHeartIcon.prefab.meta
RunInBoots/Assets/Scripts/UI/SpawnUI.cs
RunInBoots/Assets/Scripts/Utility/EventUtils.cs

---
---
linter.yml:
---
name: Lint
push: null
jobs:
build:
name: Lint
permissions:
contents: read
packages: read
steps:
with:
fetch-depth: 0
env:

[TASK-P76] Fix LifeUI in Spawn Event

---

RunInBoots/Assets/Scripts/UnitModules/TransformModule.cs

---
---
linter.yml:
---
name: Lint
push: null
jobs:
build:
name: Lint
permissions:
contents: read
packages: read
steps:
with:
fetch-depth: 0
env:

[ISSUE-B27] Remove temporary list

---

RunInBoots/Assets/Scripts/Objects/Catnip.cs
RunInBoots/Assets/Scripts/Objects/GoalPoint.cs
RunInBoots/Assets/Scripts/StageModule/StageCamera.cs
RunInBoots/Assets/Scripts/States/StageState.cs
RunInBoots/Assets/Scripts/UIConst.cs
RunInBoots/Assets/Scripts/UnitModules/TransformModule.cs
RunInBoots/Assets/Scripts/Utility/EventUtils.cs

---
---
linter.yml:
---
name: Lint
push: null
jobs:
build:
name: Lint
permissions:
contents: read
packages: read
steps:
with:
fetch-depth: 0
env:

[ISSUE-B30] additional implementation in events

---

RunInBoots/Assets/Scripts/UnitModules/StretchModule.cs

[ISSUE-B29] Apply RayOffset to StretchModule

---

RunInBoots/Assets/Scripts/Objects/GoalPoint.cs
RunInBoots/Assets/Scripts/StageModule/StageCamera.cs

---
---
linter.yml:
---
name: Lint
push: null
jobs:
build:
name: Lint
permissions:
contents: read
packages: read
steps:
with:
fetch-depth: 0
env:

[ISSUE-B37] Implement Camera ZoomIn for Clear Event

---

RunInBoots/Assets/Resources/LevelObject/MountainDrop_5X1.prefab
RunInBoots/Assets/Scripts/LevelDesignTool/DropBlockManager.cs
RunInBoots/UserSettings/EditorUserSettings.asset

trigger 동작 시 블록과 PC의 position.y 비교 시 offset을 추가하여 간헐적인 trigger 미동작 문제를 해결합니다.
추가로, drop block이 화면 밖으로 나간 후 reset 되었을 때 trigger가 동작하지 않는 문제가 추가로 발견되어 이를 해결합니다.
close #107

[ISSUE-B33] Fix DropBlock Collider logic
